version: '3.7'

services: 
  django_project:
    container_name: django_project
    build: 
      context: .
    ports: 
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static:/static

  nginx:
    container_name: nginx
    build: ./nginx
    volumes: 
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_project

volumes:
  static:
